name: Prototype Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - uses: burrunan/gradle-cache-action@v1
      name: Test Elegant Objects
      with:
        arguments: test
        gradle-version: wrapper
    - name: Build Elegant Objects
      run: ./gradlew build
